import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Reorbe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins`}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
